name: Flutter web deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release -t lib/main.dart
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
